version: '2'
services:
  mongo:
    image: mongo:3.4.3
    networks:
      my_net:
        ipv4_address: 172.18.0.2

  jenkins:
    image: cjhuang/jenkins
    volumes:
      - /home/[USER NAME]/Desktop/jenkins/data:/var/jenkins_home
    networks:
      my_net:
        ipv4_address: 172.18.0.3
    depends_on:
      - "mongo"

networks:
  my_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16